# Generated by Django 3.1.2 on 2020-10-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
