# Generated by Django 3.1.2 on 2020-11-02 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_users_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7335d764-44e1-4188-9ea9-6ac7692d61dc')),
        ),
    ]
