# Generated by Django 3.1.2 on 2020-11-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_users_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='uuid',
        ),
        migrations.AddField(
            model_name='users',
            name='url',
            field=models.CharField(default='jhu56nj6nhisdvdsgasbfjhtd9675nzczdfdmgsrg9350dfjdsg', max_length=255),
            preserve_default=False,
        ),
    ]
