# Generated by Django 3.1.2 on 2020-11-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0009_packages_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.CharField(default='xbdgcnhgkuj43576ridtydo705/*9rhtjyr', max_length=255),
            preserve_default=False,
        ),
    ]
