# Generated by Django 3.1.2 on 2020-11-10 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='visibility',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='services',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='visibility',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_updated',
            field=models.DateField(null=True),
        ),
    ]
