# Generated by Django 3.1.2 on 2020-11-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0013_auto_20201110_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='uploads/thumbnail.png', upload_to='uploads/categories/'),
        ),
    ]
