# Generated by Django 3.1.2 on 2021-02-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0017_auto_20201230_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='Rjd9jd8XrdlGgt3ZeszVfnuN61KsPMAC', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='url',
            field=models.CharField(default='LlylFW4K2hCVQPrbJPTTnidFOX0bwn6x', max_length=255),
        ),
    ]
