# Generated by Django 3.1.2 on 2021-02-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0018_auto_20210206_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='staff',
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='P4VivJ5iQMujltnW61CFT6vEjIL7Rc13', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='url',
            field=models.CharField(default='zLxJbek0NFoeSYTHzS7TXEuMidCOiVXB', max_length=255),
        ),
    ]
