# Generated by Django 3.1.2 on 2021-02-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0020_auto_20210206_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='avcVdACh6g3DkebH7har60bh2lcpFezH', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='url',
            field=models.CharField(default='pWGGfb8QV49SHaxIdngK3VNICeX5JDuC', max_length=255),
        ),
    ]
