# Generated by Django 3.1.2 on 2021-02-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0023_auto_20210219_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='fkglkE3CbnuOTQrxcBDn8Jxt3afrsFlm', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='url',
            field=models.CharField(default='s3GY0p0FCMGfFek6RPYkT7UwmNSNeaxh', max_length=255),
        ),
    ]
